sudo: false
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - libhdf5-dev
matrix:
  include:
    - perl: "5.22"
      env: COVERALLS=1 # to make purpose in Travis-CI view obvious
      before_install:
        - "cpanm -n Devel::Cover"
        - "cpanm -n Devel::Cover::Report::Coveralls"
      after_script: perl Makefile.PL && make && cover -gcov -ignore_re 'const-.*' -ignore_re '.*inline.h' -select 'HDF5.xs' -select 'blib/lib/Data/HDF5.pm' -test
