sudo: false
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
os:
  - linux
before_install:
  - "cpanm -n Devel::Cover"
  - "cpanm -n Devel::Cover::Report::Coveralls"
  #- eval $(curl https://travis-perl.github.io/init) --auto
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - libhdf5-dev
matrix:
  include:
    - perl: "5.22"
      after_script: perl Makefile.PL && make && cover -test -ignore_re '.*inline.h' -ignore_re 'const-.*'
