/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of HDFPerl.xs. Do not edit this file, edit HDFPerl.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "HDFPerl.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"
#include "hdf5.h"
#include "H5LT.h"

#line 19 "HDFPerl.c"

XS(XS_HDFPerl_h5acreate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5acreate_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5acreate_p(loc_id, name, type_id, space_id, create_plist)");
    {
	int	loc_id = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	type_id = (int)SvIV(ST(2));
	int	space_id = (int)SvIV(ST(3));
	int	create_plist = (int)SvIV(ST(4));
	int	RETVAL;
	dXSTARG;
#line 21 "HDFPerl.xs"
		RETVAL = H5Acreate(loc_id, name, type_id, space_id, create_plist);
#line 37 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5awrite_string_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5awrite_string_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5awrite_string_p(loc_id, name, buffer)");
    {
	int	loc_id = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	char *	buffer = (char *)SvPV_nolen(ST(2));
#line 32 "HDFPerl.xs"
		int attr_type;
		int attr_space;
		int attr_id;
		int string_size;
#line 59 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;
#line 37 "HDFPerl.xs"
		string_size = strlen(buffer);
		attr_space = H5Screate(H5S_SCALAR);
		attr_type = H5Tcopy(H5T_C_S1);
		H5Tset_size(attr_type, string_size);
		H5Tset_strpad(attr_type, H5T_STR_NULLTERM);
		attr_id= H5Acreate(loc_id, name, attr_type, attr_space, H5P_DEFAULT);
		H5Awrite(attr_id, attr_type, buffer);
		RETVAL = H5Aclose(attr_id);
#line 71 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5awrite_int8_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5awrite_int8_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5awrite_int8_p(attr_id, mem_type_id, buffer)");
    {
	int	attr_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	AV *	buffer;
#line 54 "HDFPerl.xs"
                int len, i;
                SV ** elem;
                char *data;
#line 92 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(2)) && SvTYPE(SvRV(ST(2)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(2));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 58 "HDFPerl.xs"
                len = av_len(buffer) + 1;
                data = (char *) malloc(len * sizeof(char));
                for (i = 0; i < len; i++) {
                        elem = av_fetch(buffer, i, 0);
                        data[i] = (char) SvIV(*elem);
                }
                RETVAL = H5Awrite(attr_id, mem_type_id, data);
                free(data); 
#line 109 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aread_int8_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aread_int8_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aread_int8_p(attr_id, mem_type_id)");
    {
	int	attr_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
#line 74 "HDFPerl.xs"
                AV * data;
                char *read_data;
                int npoints;
                int i;
                int attr_space_id;
                SV *elem;

#line 133 "HDFPerl.c"
	AV *	RETVAL;
#line 82 "HDFPerl.xs"
                if (attr_id < 0)
                        XSRETURN_UNDEF;
#line 138 "HDFPerl.c"
#line 85 "HDFPerl.xs"
                data = newAV();
                attr_space_id = H5Aget_space(attr_id);
                npoints = H5Sget_select_npoints(attr_space_id);
                read_data = (char *) malloc(sizeof(char) * npoints);

                H5Aread(attr_id, mem_type_id, read_data);

                for (i = 0; i < npoints; i++) {
                                elem = newSViv(read_data[i]);
                                av_store(data, i, elem);
                }
                RETVAL = data;
                free(read_data);
#line 153 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aclose_p(attr_id)");
    {
	int	attr_id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 107 "HDFPerl.xs"
		RETVAL = H5Aclose(attr_id);	
#line 173 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aopen_name_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aopen_name_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aopen_name_p(loc_id, name)");
    {
	int	loc_id = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 118 "HDFPerl.xs"
		RETVAL = H5Aopen_name(loc_id, name);
#line 193 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aopen_idx_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aopen_idx_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aopen_idx_p(loc_id, idx)");
    {
	int	loc_id = (int)SvIV(ST(0));
	int	idx = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 127 "HDFPerl.xs"
		RETVAL = H5Aopen_idx(loc_id, idx);
#line 213 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aget_space_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aget_space_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aget_space_p(attr_id)");
    {
	int	attr_id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 135 "HDFPerl.xs"
		RETVAL = H5Aget_space(attr_id);
#line 232 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aget_type_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aget_type_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aget_type_p(attr_id)");
    {
	int	attr_id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 143 "HDFPerl.xs"
		RETVAL = H5Aget_type(attr_id);
#line 251 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5aget_num_attrs_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5aget_num_attrs_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5aget_num_attrs_p(attr_id)");
    {
	int	attr_id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 151 "HDFPerl.xs"
		RETVAL = H5Aget_num_attrs(attr_id);
#line 270 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fcreate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fcreate_p)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fcreate_p(x, flag, create_id, access_id)");
    {
	char *	x = (char *)SvPV_nolen(ST(0));
	int	flag = (int)SvIV(ST(1));
	int	create_id = (int)SvIV(ST(2));
	int	access_id = (int)SvIV(ST(3));
	int	RETVAL;
	dXSTARG;
#line 163 "HDFPerl.xs"
		RETVAL = H5Fcreate(x, flag, create_id, access_id);
#line 292 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fopen_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fopen_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fopen_p(name, flag, access_id)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	int	flag = (int)SvIV(ST(1));
	int	access_id = (int)SvIV(ST(2));
	int	RETVAL;
	dXSTARG;
#line 173 "HDFPerl.xs"
		RETVAL = H5Fopen(name, flag, access_id);
#line 313 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fclose_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 181 "HDFPerl.xs"
		RETVAL = H5Fclose(id);
#line 332 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fflush_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fflush_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fflush_p(id, scope)");
    {
	int	id = (int)SvIV(ST(0));
	int	scope = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 190 "HDFPerl.xs"
		RETVAL = H5Fflush(id, scope);
#line 352 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gcreate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gcreate_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gcreate_p(loc, name, hint)");
    {
	int	loc = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	hint = (int)SvIV(ST(2));
	int	RETVAL;
	dXSTARG;
#line 202 "HDFPerl.xs"
		RETVAL = H5Gcreate(loc, name, hint);
#line 373 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gopen_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gopen_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gopen_p(id, name)");
    {
	int	id = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 211 "HDFPerl.xs"
		RETVAL = H5Gopen(id, name);
#line 393 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gclose_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 219 "HDFPerl.xs"
		RETVAL = H5Gclose(id);
#line 412 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gset_comment_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gset_comment_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gset_comment_p(loc, name, comment)");
    {
	int	loc = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	char *	comment = (char *)SvPV_nolen(ST(2));
	int	RETVAL;
	dXSTARG;
#line 229 "HDFPerl.xs"
		RETVAL = H5Gset_comment(loc, name, comment);
#line 433 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gget_num_objs_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gget_num_objs_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gget_num_objs_p(loc)");
    {
	int	loc = (int)SvIV(ST(0));
	SV *	RETVAL;
#line 237 "HDFPerl.xs"
                SV *data;
                hsize_t *number;

#line 453 "HDFPerl.c"
#line 241 "HDFPerl.xs"
                number = (hsize_t *)malloc(sizeof(hsize_t));
		H5Gget_num_objs(loc, number);
                data = newSViv(*number);
                RETVAL = data;
                free(number);
#line 460 "HDFPerl.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gget_objname_by_idx_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gget_objname_by_idx_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gget_objname_by_idx_p(loc, index, size)");
    {
	int	loc = (int)SvIV(ST(0));
	int	index = (int)SvIV(ST(1));
	int	size = (int)SvIV(ST(2));
	SV *	RETVAL;
#line 255 "HDFPerl.xs"
                SV *data;
                char *name;

#line 483 "HDFPerl.c"
#line 259 "HDFPerl.xs"
                name = (char *)malloc(sizeof(char)*size);
                H5Gget_objname_by_idx(loc, index, name, size);
                data = newSVpv(name, 0);
                RETVAL = data;
                free(name);
#line 490 "HDFPerl.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5gget_comment_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5gget_comment_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5gget_comment_p(loc, name, bufsize)");
    {
	int	loc = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	bufsize = (int)SvIV(ST(2));
	SV *	RETVAL;
#line 273 "HDFPerl.xs"
                SV *data;
                char *comment;
                int status;

#line 514 "HDFPerl.c"
#line 278 "HDFPerl.xs"
                comment = (char *)malloc(sizeof(char)*bufsize);
                status = H5Gget_comment(loc, name, bufsize, comment);
                if (status < 0) { 
                    data = newSViv(status); 
                }
                else {
                    data = newSVpv(comment, 0);
                }
                RETVAL = data;
                free(comment);
#line 526 "HDFPerl.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pcreate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pcreate_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pcreate_p(cls_id)");
    {
	int	cls_id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 298 "HDFPerl.xs"
		RETVAL = H5Pcreate(cls_id);
#line 546 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pclose_p(cls_id)");
    {
	int	cls_id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 306 "HDFPerl.xs"
		RETVAL = H5Pclose(cls_id);
#line 565 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pset_chunk_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pset_chunk_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pset_chunk_p(plist, ndims, dims)");
    {
	int	plist = (int)SvIV(ST(0));
	int	ndims = (int)SvIV(ST(1));
	SV *	dims = ST(2);
#line 316 "HDFPerl.xs"
		hsize_t *correct_dims;
		int i = 0;
#line 585 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;
#line 319 "HDFPerl.xs"
		correct_dims = (hsize_t *) malloc(ndims * sizeof(hsize_t));
		for (i = 0; i < ndims; i++) {
			correct_dims[i] = (hsize_t)SvIV(*av_fetch((AV *)SvRV(dims), i, 0));
		}

		RETVAL = H5Pset_chunk(plist, ndims, correct_dims);
                free(correct_dims);
#line 596 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pset_deflate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pset_deflate_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pset_deflate_p(plist, level)");
    {
	int	plist = (int)SvIV(ST(0));
	int	level = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 334 "HDFPerl.xs"
		RETVAL = H5Pset_deflate(plist, level);
#line 616 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pset_szip); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pset_szip)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pset_szip(plist, options_mask, pixels_per_block)");
    {
	int	plist = (int)SvIV(ST(0));
	unsigned int	options_mask = (unsigned int)SvUV(ST(1));
	unsigned int	pixels_per_block = (unsigned int)SvUV(ST(2));
	int	RETVAL;
	dXSTARG;
#line 344 "HDFPerl.xs"
		RETVAL = H5Pset_szip(plist, options_mask, pixels_per_block);
#line 637 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pset_layout_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pset_layout_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pset_layout_p(plist, layout)");
    {
	int	plist = (int)SvIV(ST(0));
	int	layout = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 353 "HDFPerl.xs"
		RETVAL = H5Pset_layout(plist, layout);
#line 657 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pget_file_create_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pget_file_create_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pget_file_create_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 359 "HDFPerl.xs"
		RETVAL = H5P_FILE_CREATE;
#line 675 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pget_file_access_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pget_file_access_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pget_file_access_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 365 "HDFPerl.xs"
		RETVAL = H5P_FILE_ACCESS;
#line 693 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pget_dataset_create_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pget_dataset_create_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pget_dataset_create_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 371 "HDFPerl.xs"
		RETVAL = H5P_DATASET_CREATE;
#line 711 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pget_dataset_xfer_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pget_dataset_xfer_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pget_dataset_xfer_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 377 "HDFPerl.xs"
		RETVAL = H5P_DATASET_XFER;
#line 729 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pget_mount_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pget_mount_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pget_mount_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 383 "HDFPerl.xs"
		RETVAL = H5P_MOUNT;
#line 747 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pset_fill_time_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pset_fill_time_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pset_fill_time_p(plist, alloc_time)");
    {
	int	plist = (int)SvIV(ST(0));
	int	alloc_time = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 392 "HDFPerl.xs"
                RETVAL = H5Pset_fill_time(plist, alloc_time);
#line 767 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dget_fill_time_alloc_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dget_fill_time_alloc_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dget_fill_time_alloc_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 400 "HDFPerl.xs"
                RETVAL = H5D_FILL_TIME_ALLOC;
#line 785 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dcreate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dcreate_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dcreate_p(loc, name, dtype, sid, plist)");
    {
	int	loc = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	dtype = (int)SvIV(ST(2));
	int	sid = (int)SvIV(ST(3));
	int	plist = (int)SvIV(ST(4));
	int	RETVAL;
	dXSTARG;
#line 412 "HDFPerl.xs"
		RETVAL = H5Dcreate(loc, name, dtype, sid, plist);
#line 808 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dopen_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dopen_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dopen_p(loc_id, name)");
    {
	int	loc_id = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 421 "HDFPerl.xs"
		RETVAL = H5Dopen(loc_id, name);
#line 828 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dclose_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 429 "HDFPerl.xs"
		RETVAL = H5Dclose(id);
#line 847 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dget_space_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dget_space_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dget_space_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 437 "HDFPerl.xs"
		RETVAL = H5Dget_space(id);	
#line 866 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dget_type_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dget_type_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dget_type_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 445 "HDFPerl.xs"
		RETVAL = H5Dget_type(id);	
#line 885 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_double_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_double_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_double_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	AV *	buffer;
#line 458 "HDFPerl.xs"
		int len, i;
		SV ** elem;
		double *data;
#line 909 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 462 "HDFPerl.xs"
		len = av_len(buffer) + 1;
		data = (double *) malloc(len * sizeof(double));
		for (i = 0; i < len; i++) {
			elem = av_fetch(buffer, i, 0);
			data[i] = SvIV(*elem);
		}
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id,
                    file_space_id, xfer_plist, data);
                free(data);
#line 927 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_float_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_float_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_float_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	AV *	buffer;
#line 483 "HDFPerl.xs"
		int len, i;
		SV ** elem;
		float *data;
#line 951 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 487 "HDFPerl.xs"
		len = av_len(buffer) + 1;
		data = (float *) malloc(len * sizeof(float));
		for (i = 0; i < len; i++) {
			elem = av_fetch(buffer, i, 0);
			data[i] = (float) SvIV(*elem);
		}
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id,
                    file_space_id, xfer_plist, data);
                free(data);
#line 969 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_int8_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_int8_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_int8_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	AV *	buffer;
#line 508 "HDFPerl.xs"
		int len, i;
		SV ** elem;
		char *data;
#line 993 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 512 "HDFPerl.xs"
		len = av_len(buffer) + 1;
		data = (char *) malloc(len * sizeof(int));
		for (i = 0; i < len; i++) {
			elem = av_fetch(buffer, i, 0);
			data[i] = (char) SvIV(*elem);
		}
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id,
                    file_space_id, xfer_plist, data);
                free(data);
#line 1011 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_int_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_int_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_int_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	AV *	buffer;
#line 533 "HDFPerl.xs"
		int len, i;
		SV ** elem;
		int *data;
#line 1035 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 537 "HDFPerl.xs"
		len = av_len(buffer) + 1;
		data = (int *) malloc(len * sizeof(int));
		for (i = 0; i < len; i++) {
			elem = av_fetch(buffer, i, 0);
			data[i] = SvIV(*elem);
		}
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id,
                    file_space_id, xfer_plist, data);
                free(data);
#line 1053 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_char_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_char_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_char_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	char *	buffer = (char *)SvPV_nolen(ST(5));
	int	RETVAL;
	dXSTARG;
#line 558 "HDFPerl.xs"
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id, file_space_id,
				xfer_plist, buffer);
#line 1078 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_string_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_string_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_string_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	AV *	buffer;
#line 572 "HDFPerl.xs"
		int len, i;
		SV ** elem;
		char *data;
#line 1102 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 576 "HDFPerl.xs"
		len = av_len(buffer) + 1;
		data = (char *) calloc(len,  H5Tget_size(mem_type_id));
		for (i = 0; i < len; i++) {
			elem = av_fetch(buffer, i, 0);
			/*memcpy(data + i * H5Tget_size(mem_type_id), SvPV(*elem, PL_na),*/
			memcpy(data + i * H5Tget_size(mem_type_id),
                            SvPV(*elem, PL_na),
                            H5Tget_size(mem_type_id));
		}
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id,
                    file_space_id, xfer_plist, data);
                free(data);
#line 1123 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dwrite_vlstring_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dwrite_vlstring_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dwrite_vlstring_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist, buffer)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
	AV *	buffer;
#line 600 "HDFPerl.xs"
		int len, i;
		SV **elem;
		char **data;
#line 1147 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    buffer = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "buffer is not an array reference");
#line 604 "HDFPerl.xs"
		len = av_len(buffer) + 1;
		data = (char **) malloc(len*sizeof(char *));
		for (i = 0; i < len; i++) {
			elem = av_fetch(buffer, i, 0);
			data[i] = SvPV(*elem, PL_na);
		}
		RETVAL = H5Dwrite(dataset_id, mem_type_id, mem_space_id,
                    file_space_id, xfer_plist, data);
                free(data);
#line 1165 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dread_int8_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dread_int8_p)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dread_int8_p(dataset_id, mem_space_id, file_space_id, xfer_plist)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_space_id = (int)SvIV(ST(1));
	int	file_space_id = (int)SvIV(ST(2));
	int	xfer_plist = (int)SvIV(ST(3));
#line 623 "HDFPerl.xs"
		AV * data;
		char *read_data;	
		int npoints;
		int i;
		SV *elem;

#line 1190 "HDFPerl.c"
	AV *	RETVAL;
#line 630 "HDFPerl.xs"
		if (dataset_id < 0)
			XSRETURN_UNDEF;
#line 1195 "HDFPerl.c"
#line 633 "HDFPerl.xs"
		data = newAV();
		npoints = H5Sget_select_npoints(file_space_id);
		read_data = (char *) malloc(sizeof(char) * npoints);

		H5Dread(dataset_id, H5T_NATIVE_CHAR, mem_space_id,
                    file_space_id, xfer_plist, read_data);

		for (i = 0; i < npoints; i++) {
				elem = newSViv(read_data[i]);
				av_store(data, i, elem);
		}
		RETVAL = data;
                free(read_data);
#line 1210 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dread_int_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dread_int_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dread_int_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
#line 657 "HDFPerl.xs"
		AV * data;

#line 1233 "HDFPerl.c"
	AV *	RETVAL;
#line 660 "HDFPerl.xs"
		int *read_data;	
		int npoints;
		int i;
		SV *elem;
#line 1240 "HDFPerl.c"
#line 665 "HDFPerl.xs"
		data = newAV();
		npoints = H5Sget_select_npoints(file_space_id);
		read_data = (int *) malloc(sizeof(int) * npoints);

		H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
                    xfer_plist,	read_data);

		for (i = 0; i < npoints; i++) {
				elem = newSViv(read_data[i]);
				av_store(data, i, elem);
		}
		RETVAL = data;
                free(read_data);
#line 1255 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dread_double_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dread_double_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dread_double_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
#line 689 "HDFPerl.xs"
		AV * data;

#line 1278 "HDFPerl.c"
	AV *	RETVAL;
#line 692 "HDFPerl.xs"
		double *read_data;	
		int npoints;
		int i;
		SV *elem;
#line 1285 "HDFPerl.c"
#line 697 "HDFPerl.xs"
		data = newAV();
		npoints = H5Sget_select_npoints(file_space_id);
		read_data = (double *) malloc(sizeof(double) * npoints);

		H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
                    xfer_plist, read_data);

		for (i = 0; i < npoints; i++) {
				elem = newSVnv(read_data[i]);
				av_store(data, i, elem);
		}
		RETVAL = data;
                free(read_data);
#line 1300 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dread_string_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dread_string_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dread_string_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
#line 721 "HDFPerl.xs"
                AV * data;

#line 1323 "HDFPerl.c"
	AV *	RETVAL;
#line 724 "HDFPerl.xs"
                char *read_data;
                int npoints;
                int i;
                int len; 
                SV *elem;
#line 1331 "HDFPerl.c"
#line 730 "HDFPerl.xs"
                data = newAV();
                npoints = H5Sget_select_npoints(file_space_id);
                /* mem_type_id = H5Dget_type(dataset_id);*/
                len=0;
                if (H5Tequal(H5T_NATIVE_CHAR, mem_type_id)>0)
                    len = 1;
                read_data = (char *) malloc(H5Tget_size(mem_type_id) * npoints);

                H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
                    xfer_plist, read_data);

                for (i = 0; i < npoints; i++) {
                     elem = newSVpv(&read_data[i*H5Tget_size(mem_type_id)], len);
                                av_store(data, i, elem);
                }
                RETVAL = data;
                free(read_data);
#line 1350 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dread_vlstring_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dread_vlstring_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dread_vlstring_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
#line 758 "HDFPerl.xs"
                AV * data;

#line 1373 "HDFPerl.c"
	AV *	RETVAL;
#line 761 "HDFPerl.xs"
                char **read_data;
                int npoints;
                int i;
                SV *elem;
#line 1380 "HDFPerl.c"
#line 766 "HDFPerl.xs"
                data = newAV();
                npoints = H5Sget_select_npoints(file_space_id);
                read_data = (char **) malloc(sizeof(char *) * npoints);

                H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
                    xfer_plist, read_data);

                for (i = 0; i < npoints; i++) {
                                elem = newSVpv(read_data[i], 0);
                                av_store(data, i, elem);
                }
                RETVAL = data;
                free(read_data);
#line 1395 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dread_char_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dread_char_p)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dread_char_p(dataset_id, mem_type_id, mem_space_id, file_space_id, xfer_plist)");
    {
	int	dataset_id = (int)SvIV(ST(0));
	int	mem_type_id = (int)SvIV(ST(1));
	int	mem_space_id = (int)SvIV(ST(2));
	int	file_space_id = (int)SvIV(ST(3));
	int	xfer_plist = (int)SvIV(ST(4));
#line 790 "HDFPerl.xs"
	        AV * data;

#line 1418 "HDFPerl.c"
	SV *	RETVAL;
#line 793 "HDFPerl.xs"
	        char *read_data;
                int npoints;
                SV *elem;

#line 1425 "HDFPerl.c"
#line 798 "HDFPerl.xs"
                data = newAV();
                npoints = H5Sget_select_npoints(file_space_id);
                read_data = (char *) malloc(H5Tget_size(mem_type_id) * (npoints+1));

                H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
                    xfer_plist, read_data);
                read_data[npoints+1]='\0';
                elem = newSVpv(read_data, 0);
               /* for (i = 0; i < npoints; i++) {
                                elem = newSVpv(&read_data[i*H5Tget_size(mem_type_id)], 1);
                                av_store(data, i, elem);
                }*/
                RETVAL = elem;
                free(read_data); 
#line 1441 "HDFPerl.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dextend_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dextend_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dextend_p(dset_id, dims)");
    {
	int	dset_id = (int)SvIV(ST(0));
	AV *	dims;
#line 821 "HDFPerl.xs"
                hsize_t *correct_dims;
                int i, rank;
                SV **elem;

#line 1463 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(1)) && SvTYPE(SvRV(ST(1)))==SVt_PVAV)
	    dims = (AV*)SvRV(ST(1));
	else
	    Perl_croak(aTHX_ "dims is not an array reference");
#line 826 "HDFPerl.xs"
		rank = av_len(dims)+1;
                correct_dims = (hsize_t *) malloc(rank * sizeof(hsize_t));
                for (i = 0; i < rank; i++) {
			elem = av_fetch(dims, i, 0);
			correct_dims[i] = SvIV(*elem);
                }

                RETVAL = H5Dextend(dset_id, correct_dims);
                free(correct_dims);
#line 1481 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5screate_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5screate_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5screate_p(rank, dims)");
    {
	int	rank = (int)SvIV(ST(0));
	SV *	dims = ST(1);
	int	RETVAL;
	dXSTARG;
#line 844 "HDFPerl.xs"
                hsize_t *correct_dims;
                int i = 0;
#line 1502 "HDFPerl.c"
#line 847 "HDFPerl.xs"
                correct_dims = (hsize_t *) malloc(rank * sizeof(hsize_t));
                for (i = 0; i < rank; i++) {
                        correct_dims[i] = (hsize_t)SvIV(*av_fetch((AV *)SvRV(dims), i, 0));
                }

                RETVAL = H5Screate_simple(rank, correct_dims, NULL);
                free(correct_dims);
#line 1511 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5screate_simple_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5screate_simple_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5screate_simple_p(rank, dims, maxdims)");
    {
	int	rank = (int)SvIV(ST(0));
	SV *	dims = ST(1);
	SV *	maxdims = ST(2);
	int	RETVAL;
	dXSTARG;
#line 864 "HDFPerl.xs"
		hsize_t *correct_dims;
		hsize_t *correct_maxdims;
		int i = 0;
#line 1534 "HDFPerl.c"
#line 868 "HDFPerl.xs"
		correct_dims = (hsize_t *) malloc(rank * sizeof(hsize_t));
		correct_maxdims = (hsize_t *) malloc(rank * sizeof(hsize_t));
		for (i = 0; i < rank; i++) {
			correct_dims[i] = (hsize_t)SvIV(*av_fetch((AV *)SvRV(dims), i, 0));
			correct_maxdims[i] = (hsize_t)SvIV(*av_fetch((AV *)SvRV(maxdims), i, 0));
		}

		RETVAL = H5Screate_simple(rank, correct_dims, correct_maxdims);
		free(correct_dims);
		free(correct_maxdims);
#line 1546 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5sselect_hyperslab_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5sselect_hyperslab_p)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5sselect_hyperslab_p(space_id, op, start, stride, count, block)");
    {
	int	space_id = (int)SvIV(ST(0));
	int	op = (int)SvIV(ST(1));
	AV *	start;
	AV *	stride;
	AV *	count;
	AV *	block;
#line 890 "HDFPerl.xs"
		hsize_t *correct_start;
		hsize_t *correct_stride;
		hsize_t *correct_count;
		hsize_t *correct_block;
		int len;
		int i;
                SV **elem;

#line 1575 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(2)) && SvTYPE(SvRV(ST(2)))==SVt_PVAV)
	    start = (AV*)SvRV(ST(2));
	else
	    Perl_croak(aTHX_ "start is not an array reference");

	if (SvROK(ST(3)) && SvTYPE(SvRV(ST(3)))==SVt_PVAV)
	    stride = (AV*)SvRV(ST(3));
	else
	    Perl_croak(aTHX_ "stride is not an array reference");

	if (SvROK(ST(4)) && SvTYPE(SvRV(ST(4)))==SVt_PVAV)
	    count = (AV*)SvRV(ST(4));
	else
	    Perl_croak(aTHX_ "count is not an array reference");

	if (SvROK(ST(5)) && SvTYPE(SvRV(ST(5)))==SVt_PVAV)
	    block = (AV*)SvRV(ST(5));
	else
	    Perl_croak(aTHX_ "block is not an array reference");
#line 899 "HDFPerl.xs"
		len = av_len(start) + 1;
                correct_start = (hsize_t *) malloc(len * sizeof(hsize_t));
		correct_stride = (hsize_t *) malloc(len * sizeof(hsize_t));
		correct_count = (hsize_t *) malloc(len * sizeof(hsize_t));
		correct_block = (hsize_t *) malloc(len * sizeof(hsize_t));

		for (i = 0; i < len; i++) {
			elem = av_fetch(start, i, 0);
			correct_start[i] = SvIV(*elem);
			elem = av_fetch(stride, i, 0);
			correct_stride[i] = SvIV(*elem);
			elem = av_fetch(count, i, 0);
			correct_count[i] = SvIV(*elem);
			elem = av_fetch(block, i, 0);
			correct_block[i] = SvIV(*elem);
		}

		RETVAL = H5Sselect_hyperslab(space_id, op, correct_start, correct_stride,
				correct_count, correct_block);
		free(correct_start);
		free(correct_stride);
		free(correct_count);
		free(correct_block);
#line 1622 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5sget_simple_extent_dims_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5sget_simple_extent_dims_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5sget_simple_extent_dims_p(space_id)");
    {
	int	space_id = (int)SvIV(ST(0));
#line 929 "HDFPerl.xs"
		AV * dims;
		AV * maxdims;

#line 1641 "HDFPerl.c"
	AV *	RETVAL;
#line 933 "HDFPerl.xs"
		hsize_t *read_dims;	
		hsize_t *read_maxdims;	
		int rank;
		int i;
		SV *elem;
#line 1649 "HDFPerl.c"
#line 939 "HDFPerl.xs"
		dims = newAV();
		maxdims = newAV();
                rank = H5Sget_simple_extent_ndims(space_id);
		read_dims = (hsize_t *) malloc(sizeof(hsize_t) * rank);
		read_maxdims = (hsize_t *) malloc(sizeof(hsize_t) * rank);

                H5Sget_simple_extent_dims(space_id, read_dims, read_maxdims);

		for (i = 0; i < rank; i++) {
                                elem = newSViv(read_dims[i]);
				av_store(dims, i, elem);

                                elem = newSViv(read_maxdims[i]);
				av_store(maxdims, i, elem);
		}

		RETVAL = dims;
#line 1668 "HDFPerl.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5sclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5sclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5sclose_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 968 "HDFPerl.xs"
		RETVAL = H5Sclose(id);
#line 1688 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tcreate_enum_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tcreate_enum_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tcreate_enum_p(base)");
    {
	int	base = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 979 "HDFPerl.xs"
		RETVAL = H5Tenum_create(base);
#line 1707 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tenum_insert_char_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tenum_insert_char_p)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tenum_insert_char_p(type, name, value)");
    {
	int	type = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	value = (int)SvIV(ST(2));
#line 989 "HDFPerl.xs"
		char c_value;
#line 1726 "HDFPerl.c"
	int	RETVAL;
	dXSTARG;
#line 991 "HDFPerl.xs"
		c_value = (char) value;
		RETVAL = H5Tenum_insert(type, name, &c_value);
#line 1732 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tcreate_string_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tcreate_string_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tcreate_string_p(size)");
    {
	size_t	size = (size_t)SvUV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 1000 "HDFPerl.xs"
		RETVAL = H5Tcopy(H5T_C_S1);
		H5Tset_size(RETVAL, size);
#line 1752 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tcreate_compound_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tcreate_compound_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tcreate_compound_p(size)");
    {
	size_t	size = (size_t)SvUV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 1009 "HDFPerl.xs"
		RETVAL = H5Tcreate(H5T_COMPOUND, size);
		if (RETVAL < 0)
			printf("ERROR CREATING DTYPE\n");
#line 1773 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tinsert_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tinsert_p)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tinsert_p(type, name, offset, field)");
    {
	int	type = (int)SvIV(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	size_t	offset = (size_t)SvUV(ST(2));
	int	field = (int)SvIV(ST(3));
	int	RETVAL;
	dXSTARG;
#line 1022 "HDFPerl.xs"
		RETVAL = H5Tinsert((hid_t)type, name, offset, field);
#line 1795 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_native_int_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_native_int_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_native_int_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1028 "HDFPerl.xs"
		RETVAL = H5T_NATIVE_INT;
#line 1813 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_native_double_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_native_double_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_native_double_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1034 "HDFPerl.xs"
		RETVAL = H5T_NATIVE_FLOAT;
#line 1831 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_native_float_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_native_float_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_native_float_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1040 "HDFPerl.xs"
		RETVAL = H5T_NATIVE_FLOAT;
#line 1849 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_variable_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_variable_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_variable_p()");
    {
	size_t	RETVAL;
	dXSTARG;
#line 1046 "HDFPerl.xs"
		RETVAL = H5T_VARIABLE;
#line 1867 "HDFPerl.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_native_char_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_native_char_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_native_char_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1052 "HDFPerl.xs"
		RETVAL = H5T_NATIVE_CHAR;
#line 1885 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_size_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_size_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_size_p(tid)");
    {
	int	tid = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 1060 "HDFPerl.xs"
		RETVAL = H5Tget_size(tid);
#line 1904 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tcopy); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tcopy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tcopy(tid)");
    {
	int	tid = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 1068 "HDFPerl.xs"
		RETVAL = H5Tcopy(tid);
#line 1923 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tclose_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tclose_p)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tclose_p(id)");
    {
	int	id = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 1076 "HDFPerl.xs"
		RETVAL = H5Tclose(id);
#line 1942 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tequal_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tequal_p)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tequal_p(id1, id2)");
    {
	int	id1 = (int)SvIV(ST(0));
	int	id2 = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 1085 "HDFPerl.xs"
		RETVAL = H5Tequal(id1, id2);
#line 1962 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fget_ftrunc_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fget_ftrunc_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fget_ftrunc_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1094 "HDFPerl.xs"
		RETVAL = H5F_ACC_TRUNC;
#line 1980 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5pget_pdefault_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5pget_pdefault_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5pget_pdefault_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1100 "HDFPerl.xs"
		RETVAL = H5P_DEFAULT;
#line 1998 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fget_frdrw_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fget_frdrw_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fget_frdrw_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1106 "HDFPerl.xs"
		RETVAL = H5F_ACC_RDWR;
#line 2016 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fget_frdonly_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fget_frdonly_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fget_frdonly_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1112 "HDFPerl.xs"
		RETVAL = H5F_ACC_RDONLY;
#line 2034 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fget_scope_global); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fget_scope_global)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fget_scope_global()");
    {
	int	RETVAL;
	dXSTARG;
#line 1118 "HDFPerl.xs"
		RETVAL = H5F_SCOPE_GLOBAL;
#line 2052 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5fget_scope_local); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5fget_scope_local)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5fget_scope_local()");
    {
	int	RETVAL;
	dXSTARG;
#line 1124 "HDFPerl.xs"
		RETVAL = H5F_SCOPE_LOCAL;
#line 2070 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dget_compact_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dget_compact_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dget_compact_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1130 "HDFPerl.xs"
		RETVAL = H5D_COMPACT;
#line 2088 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dget_contiguous_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dget_contiguous_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dget_contiguous_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1136 "HDFPerl.xs"
		RETVAL = H5D_CONTIGUOUS;
#line 2106 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5dget_chunked_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5dget_chunked_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5dget_chunked_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1142 "HDFPerl.xs"
		RETVAL = H5D_CHUNKED;
#line 2124 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5sget_unlimited_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5sget_unlimited_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5sget_unlimited_p()");
    {
	size_t	RETVAL;
	dXSTARG;
#line 1148 "HDFPerl.xs"
                RETVAL = H5S_UNLIMITED;
#line 2142 "HDFPerl.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5sget_select_set_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5sget_select_set_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5sget_select_set_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1154 "HDFPerl.xs"
                RETVAL = H5S_SELECT_SET;
#line 2160 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_HDFPerl_h5tget_c_s1_p); /* prototype to pass -Wmissing-prototypes */
XS(XS_HDFPerl_h5tget_c_s1_p)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: HDFPerl::h5tget_c_s1_p()");
    {
	int	RETVAL;
	dXSTARG;
#line 1160 "HDFPerl.xs"
		RETVAL = H5T_C_S1;
#line 2178 "HDFPerl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_HDFPerl); /* prototype to pass -Wmissing-prototypes */
XS(boot_HDFPerl)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("HDFPerl::h5acreate_p", XS_HDFPerl_h5acreate_p, file);
        newXS("HDFPerl::h5awrite_string_p", XS_HDFPerl_h5awrite_string_p, file);
        newXS("HDFPerl::h5awrite_int8_p", XS_HDFPerl_h5awrite_int8_p, file);
        newXS("HDFPerl::h5aread_int8_p", XS_HDFPerl_h5aread_int8_p, file);
        newXS("HDFPerl::h5aclose_p", XS_HDFPerl_h5aclose_p, file);
        newXS("HDFPerl::h5aopen_name_p", XS_HDFPerl_h5aopen_name_p, file);
        newXS("HDFPerl::h5aopen_idx_p", XS_HDFPerl_h5aopen_idx_p, file);
        newXS("HDFPerl::h5aget_space_p", XS_HDFPerl_h5aget_space_p, file);
        newXS("HDFPerl::h5aget_type_p", XS_HDFPerl_h5aget_type_p, file);
        newXS("HDFPerl::h5aget_num_attrs_p", XS_HDFPerl_h5aget_num_attrs_p, file);
        newXS("HDFPerl::h5fcreate_p", XS_HDFPerl_h5fcreate_p, file);
        newXS("HDFPerl::h5fopen_p", XS_HDFPerl_h5fopen_p, file);
        newXS("HDFPerl::h5fclose_p", XS_HDFPerl_h5fclose_p, file);
        newXS("HDFPerl::h5fflush_p", XS_HDFPerl_h5fflush_p, file);
        newXS("HDFPerl::h5gcreate_p", XS_HDFPerl_h5gcreate_p, file);
        newXS("HDFPerl::h5gopen_p", XS_HDFPerl_h5gopen_p, file);
        newXS("HDFPerl::h5gclose_p", XS_HDFPerl_h5gclose_p, file);
        newXS("HDFPerl::h5gset_comment_p", XS_HDFPerl_h5gset_comment_p, file);
        newXS("HDFPerl::h5gget_num_objs_p", XS_HDFPerl_h5gget_num_objs_p, file);
        newXS("HDFPerl::h5gget_objname_by_idx_p", XS_HDFPerl_h5gget_objname_by_idx_p, file);
        newXS("HDFPerl::h5gget_comment_p", XS_HDFPerl_h5gget_comment_p, file);
        newXS("HDFPerl::h5pcreate_p", XS_HDFPerl_h5pcreate_p, file);
        newXS("HDFPerl::h5pclose_p", XS_HDFPerl_h5pclose_p, file);
        newXS("HDFPerl::h5pset_chunk_p", XS_HDFPerl_h5pset_chunk_p, file);
        newXS("HDFPerl::h5pset_deflate_p", XS_HDFPerl_h5pset_deflate_p, file);
        newXS("HDFPerl::h5pset_szip", XS_HDFPerl_h5pset_szip, file);
        newXS("HDFPerl::h5pset_layout_p", XS_HDFPerl_h5pset_layout_p, file);
        newXS("HDFPerl::h5pget_file_create_p", XS_HDFPerl_h5pget_file_create_p, file);
        newXS("HDFPerl::h5pget_file_access_p", XS_HDFPerl_h5pget_file_access_p, file);
        newXS("HDFPerl::h5pget_dataset_create_p", XS_HDFPerl_h5pget_dataset_create_p, file);
        newXS("HDFPerl::h5pget_dataset_xfer_p", XS_HDFPerl_h5pget_dataset_xfer_p, file);
        newXS("HDFPerl::h5pget_mount_p", XS_HDFPerl_h5pget_mount_p, file);
        newXS("HDFPerl::h5pset_fill_time_p", XS_HDFPerl_h5pset_fill_time_p, file);
        newXS("HDFPerl::h5dget_fill_time_alloc_p", XS_HDFPerl_h5dget_fill_time_alloc_p, file);
        newXS("HDFPerl::h5dcreate_p", XS_HDFPerl_h5dcreate_p, file);
        newXS("HDFPerl::h5dopen_p", XS_HDFPerl_h5dopen_p, file);
        newXS("HDFPerl::h5dclose_p", XS_HDFPerl_h5dclose_p, file);
        newXS("HDFPerl::h5dget_space_p", XS_HDFPerl_h5dget_space_p, file);
        newXS("HDFPerl::h5dget_type_p", XS_HDFPerl_h5dget_type_p, file);
        newXS("HDFPerl::h5dwrite_double_p", XS_HDFPerl_h5dwrite_double_p, file);
        newXS("HDFPerl::h5dwrite_float_p", XS_HDFPerl_h5dwrite_float_p, file);
        newXS("HDFPerl::h5dwrite_int8_p", XS_HDFPerl_h5dwrite_int8_p, file);
        newXS("HDFPerl::h5dwrite_int_p", XS_HDFPerl_h5dwrite_int_p, file);
        newXS("HDFPerl::h5dwrite_char_p", XS_HDFPerl_h5dwrite_char_p, file);
        newXS("HDFPerl::h5dwrite_string_p", XS_HDFPerl_h5dwrite_string_p, file);
        newXS("HDFPerl::h5dwrite_vlstring_p", XS_HDFPerl_h5dwrite_vlstring_p, file);
        newXS("HDFPerl::h5dread_int8_p", XS_HDFPerl_h5dread_int8_p, file);
        newXS("HDFPerl::h5dread_int_p", XS_HDFPerl_h5dread_int_p, file);
        newXS("HDFPerl::h5dread_double_p", XS_HDFPerl_h5dread_double_p, file);
        newXS("HDFPerl::h5dread_string_p", XS_HDFPerl_h5dread_string_p, file);
        newXS("HDFPerl::h5dread_vlstring_p", XS_HDFPerl_h5dread_vlstring_p, file);
        newXS("HDFPerl::h5dread_char_p", XS_HDFPerl_h5dread_char_p, file);
        newXS("HDFPerl::h5dextend_p", XS_HDFPerl_h5dextend_p, file);
        newXS("HDFPerl::h5screate_p", XS_HDFPerl_h5screate_p, file);
        newXS("HDFPerl::h5screate_simple_p", XS_HDFPerl_h5screate_simple_p, file);
        newXS("HDFPerl::h5sselect_hyperslab_p", XS_HDFPerl_h5sselect_hyperslab_p, file);
        newXS("HDFPerl::h5sget_simple_extent_dims_p", XS_HDFPerl_h5sget_simple_extent_dims_p, file);
        newXS("HDFPerl::h5sclose_p", XS_HDFPerl_h5sclose_p, file);
        newXS("HDFPerl::h5tcreate_enum_p", XS_HDFPerl_h5tcreate_enum_p, file);
        newXS("HDFPerl::h5tenum_insert_char_p", XS_HDFPerl_h5tenum_insert_char_p, file);
        newXS("HDFPerl::h5tcreate_string_p", XS_HDFPerl_h5tcreate_string_p, file);
        newXS("HDFPerl::h5tcreate_compound_p", XS_HDFPerl_h5tcreate_compound_p, file);
        newXS("HDFPerl::h5tinsert_p", XS_HDFPerl_h5tinsert_p, file);
        newXS("HDFPerl::h5tget_native_int_p", XS_HDFPerl_h5tget_native_int_p, file);
        newXS("HDFPerl::h5tget_native_double_p", XS_HDFPerl_h5tget_native_double_p, file);
        newXS("HDFPerl::h5tget_native_float_p", XS_HDFPerl_h5tget_native_float_p, file);
        newXS("HDFPerl::h5tget_variable_p", XS_HDFPerl_h5tget_variable_p, file);
        newXS("HDFPerl::h5tget_native_char_p", XS_HDFPerl_h5tget_native_char_p, file);
        newXS("HDFPerl::h5tget_size_p", XS_HDFPerl_h5tget_size_p, file);
        newXS("HDFPerl::h5tcopy", XS_HDFPerl_h5tcopy, file);
        newXS("HDFPerl::h5tclose_p", XS_HDFPerl_h5tclose_p, file);
        newXS("HDFPerl::h5tequal_p", XS_HDFPerl_h5tequal_p, file);
        newXS("HDFPerl::h5fget_ftrunc_p", XS_HDFPerl_h5fget_ftrunc_p, file);
        newXS("HDFPerl::h5pget_pdefault_p", XS_HDFPerl_h5pget_pdefault_p, file);
        newXS("HDFPerl::h5fget_frdrw_p", XS_HDFPerl_h5fget_frdrw_p, file);
        newXS("HDFPerl::h5fget_frdonly_p", XS_HDFPerl_h5fget_frdonly_p, file);
        newXS("HDFPerl::h5fget_scope_global", XS_HDFPerl_h5fget_scope_global, file);
        newXS("HDFPerl::h5fget_scope_local", XS_HDFPerl_h5fget_scope_local, file);
        newXS("HDFPerl::h5dget_compact_p", XS_HDFPerl_h5dget_compact_p, file);
        newXS("HDFPerl::h5dget_contiguous_p", XS_HDFPerl_h5dget_contiguous_p, file);
        newXS("HDFPerl::h5dget_chunked_p", XS_HDFPerl_h5dget_chunked_p, file);
        newXS("HDFPerl::h5sget_unlimited_p", XS_HDFPerl_h5sget_unlimited_p, file);
        newXS("HDFPerl::h5sget_select_set_p", XS_HDFPerl_h5sget_select_set_p, file);
        newXS("HDFPerl::h5tget_c_s1_p", XS_HDFPerl_h5tget_c_s1_p, file);
    XSRETURN_YES;
}

